### ISSUE TITLE
parseToDicts crashes when FAM.CHILD is empty

### ISSUE THREAD

**Issue by gruberma** [gruberma/CS555Project#28]
Traceback (most recent call last):
  File "gedcomValidater/validate.py", line 459, in <module>
    run_all_checks(sys.argv[1])
  File "gedcomValidater/validate.py", line 370, in run_all_checks
    indivs_df, families_df = gedcomParser.fileToDataframes.parseFileToDFs(filename)
  File "/home/martin/Dokumente/Studium/WS18/Agile_Methods/CS555Project/gedcomValidater/gedcomParser/fileToDataframes.py", line 19, in parseFileToDFs
    indivs, families = fileToDicts.parseFile(filename)
  File "/home/martin/Dokumente/Studium/WS18/Agile_Methods/CS555Project/gedcomValidater/gedcomParser/fileToDicts.py", line 72, in parseFile
    family["CHILDREN"].add(indi["ID"])
AttributeError: 'dict' object has no attribute 'add'

**Comment by elliot-wasem** [comment]
@gruberma where does it crash? in my parser? or in your part?

**Comment by elliot-wasem** [comment]
In this case, it should add an empty dictionary to children, allowing it to be updated properly
