### ISSUE TITLE
If there is no HUSB, WIFE, DIVORCE entry in a FAM, we should still have this column

### ISSUE THREAD

**Issue by gruberma** [gruberma/CS555Project#29]
Traceback (most recent call last):
  File "gedcomValidater/validate.py", line 459, in <module>
    run_all_checks(sys.argv[1])
  File "gedcomValidater/validate.py", line 370, in run_all_checks
    indivs_df, families_df = gedcomParser.fileToDataframes.parseFileToDFs(filename)
  File "/home/martin/Dokumente/Studium/WS18/Agile_Methods/CS555Project/gedcomValidater/gedcomParser/fileToDataframes.py", line 40, in parseFileToDFs
    families_df = families_df[fams_columns]
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2682, in __getitem__
    return self._getitem_array(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2726, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1327, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "['DIVORCED' 'HUSBAND ID' 'HUSBAND NAME'] not in index"

**Comment by elliot-wasem** [comment]
any idea where this error may be coming from @gruberma ?

**Comment by gruberma** [comment]
Just fixed it
